FROM bitnami/spark:latest
USER root
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY spark_processor.py /app/spark_processor.py
WORKDIR /app
RUN mkdir -p /app/sqlite_db /app/csv_output