FROM apache/spark:3.5.0-scala2.12-java11-ubuntu
USER root
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt
COPY spark_processor.py /app/spark_processor.py
WORKDIR /app
RUN mkdir -p /app/sqlite_db /app/csv_output