services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Usar host.docker.internal para que los clientes se conecten al host
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  spark-processor:
    build:
      context: .
      dockerfile: Dockerfile.spark
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    volumes:
      - ./sqlite_db:/app/sqlite_db
      - ./csv_output:/app/csv_output
    command: /opt/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 /app/spark_processor.py
    extra_hosts:
      - "host.docker.internal:host-gateway" # Asegura resolución en Linux también

  producer-transacciones:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    command: python /app/producers/producer_transacciones.py
    extra_hosts:
      - "host.docker.internal:host-gateway"

  producer-notificaciones:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    command: python /app/producers/producer_notificaciones.py
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    ports:
      - "5000:5000"
    command: python /app/dashboard/app.py
    extra_hosts:
      - "host.docker.internal:host-gateway"

  alert-system:
    build:
      context: .
      dockerfile: Dockerfile.alert
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    volumes:
      - ./sqlite_db:/app/sqlite_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
